// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxzRWZVOWfGcIngN7R0cGRM-ct99F7Cx0',
    appId: '1:69785479277:web:5ab8a1184fde829e79f764',
    messagingSenderId: '69785479277',
    projectId: 'fruitai-4cc33',
    authDomain: 'fruitai-4cc33.firebaseapp.com',
    storageBucket: 'fruitai-4cc33.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZjqw_Uk8_mc3WyljjzEPPZBOQpffPu_g',
    appId: '1:69785479277:android:c75e1ae726e52cdf79f764',
    messagingSenderId: '69785479277',
    projectId: 'fruitai-4cc33',
    storageBucket: 'fruitai-4cc33.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUz1VSEM9QbyHhSDtXNSpZrOT46VawKhc',
    appId: '1:69785479277:ios:e3c5ff0117f906fa79f764',
    messagingSenderId: '69785479277',
    projectId: 'fruitai-4cc33',
    storageBucket: 'fruitai-4cc33.firebasestorage.app',
    iosBundleId: 'com.example.fruitai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUz1VSEM9QbyHhSDtXNSpZrOT46VawKhc',
    appId: '1:69785479277:ios:e3c5ff0117f906fa79f764',
    messagingSenderId: '69785479277',
    projectId: 'fruitai-4cc33',
    storageBucket: 'fruitai-4cc33.firebasestorage.app',
    iosBundleId: 'com.example.fruitai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxzRWZVOWfGcIngN7R0cGRM-ct99F7Cx0',
    appId: '1:69785479277:web:989a4a4638ff425e79f764',
    messagingSenderId: '69785479277',
    projectId: 'fruitai-4cc33',
    authDomain: 'fruitai-4cc33.firebaseapp.com',
    storageBucket: 'fruitai-4cc33.firebasestorage.app',
  );
}
